(function() {var implementors = {};
implementors["account"] = [{"text":"impl Ord for EthereumSigner","synthetic":false,"types":[]}];
implementors["moonbase_runtime"] = [{"text":"impl Ord for ProxyType","synthetic":false,"types":[]}];
implementors["moonbeam_rpc_trace"] = [{"text":"impl Ord for CacheBatchId","synthetic":false,"types":[]}];
implementors["moonbeam_runtime"] = [{"text":"impl Ord for ProxyType","synthetic":false,"types":[]}];
implementors["moonriver_runtime"] = [{"text":"impl Ord for ProxyType","synthetic":false,"types":[]}];
implementors["moonshadow_runtime"] = [{"text":"impl Ord for ProxyType","synthetic":false,"types":[]}];
implementors["parachain_staking"] = [{"text":"impl&lt;AccountId:&nbsp;Ord, Balance&gt; Ord for Bond&lt;AccountId, Balance&gt;","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()