// SPDX-License-Identifier: GPL-3.0-only
pragma solidity >=0.8.0;

/// The interface through which solidity contracts will interact with pallet-democracy
/// We implement this same interface including four-byte function selectors, in the precompile that
/// wraps the pallet
interface Democracy {
    // First some simple accessors

    /// Get the total number of public proposals past and present
    function public_prop_count() external view returns (uint256);

    // Now the dispatchables

    /// Make a new proposal with the given hash locking the given value
    function propose (bytes32 proposal_hash, uint256 value) external;
}

// These are the selectors generated by remix following this advice
// https://ethereum.stackexchange.com/a/73405/9963
// Eventually we will probably want a better way of generating these and copying them to Rust
// {
// 	"7824e7d1": "propose(bytes32,uint256)",
// 	"56fdf547": "public_prop_count()"
// }
