// Copyright 2025 Moonbeam foundation
// This file is part of Moonbeam.

// Moonbeam is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Moonbeam is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Moonbeam.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_collective`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-02-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-10-0-0-176`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/production/wbuild/moonbeam-runtime/moonbeam_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --steps=50
// --repeat=20
// --pallet=pallet_collective
// --extrinsic=*
// --wasm-execution=compiled
// --header=./file_header.txt
// --template=./benchmarking/frame-weight-template.hbs
// --disable-log-color
// --output=./runtime/moonbeam/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for `pallet_collective`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collective::WeightInfo for WeightInfo<T> {
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:100 w:100)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Prime` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[0, 9]`.
	/// The range of component `n` is `[0, 9]`.
	/// The range of component `p` is `[0, 20]`.
	/// The range of component `m` is `[0, 100]`.
	/// The range of component `n` is `[0, 100]`.
	/// The range of component `p` is `[0, 100]`.
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (2021 ±0) + p * (2026 ±0)`
		//  Estimated: `12234 + m * (1231 ±14) + p * (3660 ±14)`
		// Minimum execution time: 14_762_000 picoseconds.
		Weight::from_parts(15_043_000, 12234)
			// Standard Error: 60_564
			.saturating_add(Weight::from_parts(4_525_602, 0).saturating_mul(m.into()))
			// Standard Error: 60_564
			.saturating_add(Weight::from_parts(8_688_361, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 1231).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 3660).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `145 + m * (20 ±0)`
		//  Estimated: `1630 + m * (20 ±0)`
		// Minimum execution time: 16_598_000 picoseconds.
		Weight::from_parts(16_825_399, 1630)
			// Standard Error: 120
			.saturating_add(Weight::from_parts(879, 0).saturating_mul(b.into()))
			// Standard Error: 1_241
			.saturating_add(Weight::from_parts(11_593, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `145 + m * (20 ±0)`
		//  Estimated: `3610 + m * (20 ±0)`
		// Minimum execution time: 19_427_000 picoseconds.
		Weight::from_parts(19_098_991, 3610)
			// Standard Error: 57
			.saturating_add(Weight::from_parts(1_435, 0).saturating_mul(b.into()))
			// Standard Error: 591
			.saturating_add(Weight::from_parts(19_814, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalCount` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391 + m * (20 ±0) + p * (36 ±0)`
		//  Estimated: `3785 + m * (21 ±0) + p * (36 ±0)`
		// Minimum execution time: 22_848_000 picoseconds.
		Weight::from_parts(24_128_907, 3785)
			// Standard Error: 129
			.saturating_add(Weight::from_parts(4_016, 0).saturating_mul(b.into()))
			// Standard Error: 1_346
			.saturating_add(Weight::from_parts(24_448, 0).saturating_mul(m.into()))
			// Standard Error: 1_329
			.saturating_add(Weight::from_parts(237_248, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 21).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 36).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[5, 9]`.
	/// The range of component `m` is `[5, 100]`.
	fn vote(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `866 + m * (40 ±0)`
		//  Estimated: `4330 + m * (40 ±0)`
		// Minimum execution time: 28_546_000 picoseconds.
		Weight::from_parts(29_896_528, 4330)
			// Standard Error: 613
			.saturating_add(Weight::from_parts(28_324, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `443 + m * (40 ±0) + p * (36 ±0)`
		//  Estimated: `3888 + m * (41 ±0) + p * (36 ±0)`
		// Minimum execution time: 28_012_000 picoseconds.
		Weight::from_parts(28_241_624, 3888)
			// Standard Error: 1_610
			.saturating_add(Weight::from_parts(29_631, 0).saturating_mul(m.into()))
			// Standard Error: 1_570
			.saturating_add(Weight::from_parts(219_822, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 41).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 36).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `787 + b * (1 ±0) + m * (40 ±0) + p * (40 ±0)`
		//  Estimated: `4104 + b * (1 ±0) + m * (42 ±0) + p * (40 ±0)`
		// Minimum execution time: 41_538_000 picoseconds.
		Weight::from_parts(44_759_119, 4104)
			// Standard Error: 151
			.saturating_add(Weight::from_parts(2_311, 0).saturating_mul(b.into()))
			// Standard Error: 1_604
			.saturating_add(Weight::from_parts(10_323, 0).saturating_mul(m.into()))
			// Standard Error: 1_563
			.saturating_add(Weight::from_parts(240_603, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 42).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Prime` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `512 + m * (30 ±0) + p * (36 ±0)`
		//  Estimated: `3954 + m * (31 ±0) + p * (36 ±0)`
		// Minimum execution time: 29_595_000 picoseconds.
		Weight::from_parts(29_676_325, 3954)
			// Standard Error: 999
			.saturating_add(Weight::from_parts(29_935, 0).saturating_mul(m.into()))
			// Standard Error: 974
			.saturating_add(Weight::from_parts(229_527, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 31).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 36).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Members` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Prime` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `807 + b * (1 ±0) + m * (40 ±0) + p * (40 ±0)`
		//  Estimated: `4124 + b * (1 ±0) + m * (42 ±0) + p * (40 ±0)`
		// Minimum execution time: 44_208_000 picoseconds.
		Weight::from_parts(46_951_489, 4124)
			// Standard Error: 149
			.saturating_add(Weight::from_parts(2_558, 0).saturating_mul(b.into()))
			// Standard Error: 1_576
			.saturating_add(Weight::from_parts(11_702, 0).saturating_mul(m.into()))
			// Standard Error: 1_537
			.saturating_add(Weight::from_parts(243_150, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 42).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `p` is `[1, 100]`.
	fn disapprove_proposal(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `260 + p * (32 ±0)`
		//  Estimated: `1745 + p * (32 ±0)`
		// Minimum execution time: 14_267_000 picoseconds.
		Weight::from_parts(15_485_937, 1745)
			// Standard Error: 643
			.saturating_add(Weight::from_parts(185_507, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::CostOf` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Proposals` (r:1 w:1)
	/// Proof: `OpenTechCommitteeCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::Voting` (r:0 w:1)
	/// Proof: `OpenTechCommitteeCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 100]`.
	fn kill(d: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1531 + p * (36 ±0)`
		//  Estimated: `4930 + d * (123 ±6) + p * (37 ±0)`
		// Minimum execution time: 22_805_000 picoseconds.
		Weight::from_parts(25_391_167, 4930)
			// Standard Error: 66_304
			.saturating_add(Weight::from_parts(369_978, 0).saturating_mul(d.into()))
			// Standard Error: 1_026
			.saturating_add(Weight::from_parts(231_158, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 123).saturating_mul(d.into()))
			.saturating_add(Weight::from_parts(0, 37).saturating_mul(p.into()))
	}
	/// Storage: `OpenTechCommitteeCollective::ProposalOf` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `OpenTechCommitteeCollective::CostOf` (r:1 w:0)
	/// Proof: `OpenTechCommitteeCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn release_proposal_cost() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `945`
		//  Estimated: `4410`
		// Minimum execution time: 16_633_000 picoseconds.
		Weight::from_parts(17_158_000, 4410)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}
