(function() {var implementors = {
"moonbase_runtime":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"moonbase_runtime/governance/custom_origins/trait.Config.html\" title=\"trait moonbase_runtime::governance::custom_origins::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"moonbase_runtime/governance/custom_origins/struct.Pallet.html\" title=\"struct moonbase_runtime::governance::custom_origins::Pallet\">Pallet</a>&lt;T&gt;"]],
"moonriver_runtime":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"moonriver_runtime/governance/custom_origins/trait.Config.html\" title=\"trait moonriver_runtime::governance::custom_origins::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"moonriver_runtime/governance/custom_origins/struct.Pallet.html\" title=\"struct moonriver_runtime::governance::custom_origins::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_asset_manager":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_asset_manager/pallet/trait.Config.html\" title=\"trait pallet_asset_manager::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_asset_manager/pallet/struct.Pallet.html\" title=\"struct pallet_asset_manager::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_author_mapping":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_author_mapping/pallet/trait.Config.html\" title=\"trait pallet_author_mapping::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_author_mapping/pallet/struct.Pallet.html\" title=\"struct pallet_author_mapping::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_erc20_xcm_bridge":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_erc20_xcm_bridge/pallet/trait.Config.html\" title=\"trait pallet_erc20_xcm_bridge::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_erc20_xcm_bridge/pallet/struct.Pallet.html\" title=\"struct pallet_erc20_xcm_bridge::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_ethereum_chain_id":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_ethereum_chain_id/pallet/trait.Config.html\" title=\"trait pallet_ethereum_chain_id::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_ethereum_chain_id/pallet/struct.Pallet.html\" title=\"struct pallet_ethereum_chain_id::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_ethereum_xcm":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_ethereum_xcm/pallet/trait.Config.html\" title=\"trait pallet_ethereum_xcm::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_ethereum_xcm/pallet/struct.Pallet.html\" title=\"struct pallet_ethereum_xcm::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_maintenance_mode":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_maintenance_mode/pallet/trait.Config.html\" title=\"trait pallet_maintenance_mode::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_maintenance_mode/pallet/struct.Pallet.html\" title=\"struct pallet_maintenance_mode::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_migrations":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_migrations/pallet/trait.Config.html\" title=\"trait pallet_migrations::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_migrations/pallet/struct.Pallet.html\" title=\"struct pallet_migrations::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_moonbeam_orbiters":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_moonbeam_orbiters/pallet/trait.Config.html\" title=\"trait pallet_moonbeam_orbiters::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_moonbeam_orbiters/pallet/struct.Pallet.html\" title=\"struct pallet_moonbeam_orbiters::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_parachain_staking":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_parachain_staking/pallet/trait.Config.html\" title=\"trait pallet_parachain_staking::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_parachain_staking/pallet/struct.Pallet.html\" title=\"struct pallet_parachain_staking::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_proxy_genesis_companion":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_proxy_genesis_companion/pallet/trait.Config.html\" title=\"trait pallet_proxy_genesis_companion::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_proxy_genesis_companion/pallet/struct.Pallet.html\" title=\"struct pallet_proxy_genesis_companion::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_randomness":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_randomness/pallet/trait.Config.html\" title=\"trait pallet_randomness::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_randomness/pallet/struct.Pallet.html\" title=\"struct pallet_randomness::pallet::Pallet\">Pallet</a>&lt;T&gt;"]],
"pallet_xcm_transactor":[["impl&lt;T:&nbsp;<a class=\"trait\" href=\"pallet_xcm_transactor/pallet/trait.Config.html\" title=\"trait pallet_xcm_transactor::pallet::Config\">Config</a>&gt; Hooks&lt;&lt;T as Config&gt;::BlockNumber&gt; for <a class=\"struct\" href=\"pallet_xcm_transactor/pallet/struct.Pallet.html\" title=\"struct pallet_xcm_transactor::pallet::Pallet\">Pallet</a>&lt;T&gt;"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()