// Copyright 2025 Moonbeam foundation
// This file is part of Moonbeam.

// Moonbeam is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Moonbeam is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Moonbeam.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_collective`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.2.0
//! DATE: 2025-07-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-10-0-0-36`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime=./target/production/wbuild/moonriver-runtime/moonriver_runtime.wasm
// --genesis-builder=runtime
// --genesis-builder-preset=development
// --steps=50
// --repeat=20
// --pallet=pallet_collective
// --extrinsic=*
// --wasm-execution=compiled
// --header=./file_header.txt
// --template=./benchmarking/frame-weight-template.hbs
// --output=./runtime/moonriver/src/weights

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for `pallet_collective`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collective::WeightInfo for WeightInfo<T> {
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Voting` (r:20 w:20)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Prime` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[0, 9]`.
	/// The range of component `n` is `[0, 9]`.
	/// The range of component `p` is `[0, 20]`.
	/// The range of component `m` is `[0, 100]`.
	/// The range of component `n` is `[0, 100]`.
	/// The range of component `p` is `[0, 100]`.
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (425 ±0) + p * (206 ±0)`
		//  Estimated: `4183 + m * (266 ±4) + p * (2556 ±2)`
		// Minimum execution time: 8_621_000 picoseconds.
		Weight::from_parts(8_929_000, 4183)
			// Standard Error: 98_357
			.saturating_add(Weight::from_parts(3_071_314, 0).saturating_mul(m.into()))
			// Standard Error: 44_937
			.saturating_add(Weight::from_parts(3_861_812, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 266).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2556).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281 + m * (20 ±0)`
		//  Estimated: `1765 + m * (20 ±0)`
		// Minimum execution time: 17_034_000 picoseconds.
		Weight::from_parts(17_130_852, 1765)
			// Standard Error: 63
			.saturating_add(Weight::from_parts(1_873, 0).saturating_mul(b.into()))
			// Standard Error: 7_501
			.saturating_add(Weight::from_parts(156_050, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 100]`.
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `281 + m * (20 ±0)`
		//  Estimated: `3745 + m * (20 ±0)`
		// Minimum execution time: 19_561_000 picoseconds.
		Weight::from_parts(19_720_532, 3745)
			// Standard Error: 64
			.saturating_add(Weight::from_parts(1_811, 0).saturating_mul(b.into()))
			// Standard Error: 7_706
			.saturating_add(Weight::from_parts(157_856, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalCount` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `193 + m * (20 ±0) + p * (55 ±0)`
		//  Estimated: `3614 + m * (27 ±0) + p * (54 ±0)`
		// Minimum execution time: 20_372_000 picoseconds.
		Weight::from_parts(21_165_781, 3614)
			// Standard Error: 89
			.saturating_add(Weight::from_parts(3_028, 0).saturating_mul(b.into()))
			// Standard Error: 12_209
			.saturating_add(Weight::from_parts(108_789, 0).saturating_mul(m.into()))
			// Standard Error: 4_683
			.saturating_add(Weight::from_parts(384_604, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 27).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 54).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[5, 9]`.
	/// The range of component `m` is `[5, 100]`.
	fn vote(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `767 + m * (40 ±0)`
		//  Estimated: `4232 + m * (40 ±0)`
		// Minimum execution time: 22_204_000 picoseconds.
		Weight::from_parts(23_377_934, 4232)
			// Standard Error: 9_303
			.saturating_add(Weight::from_parts(29_654, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `300 + m * (40 ±0) + p * (55 ±0)`
		//  Estimated: `3762 + m * (43 ±0) + p * (55 ±0)`
		// Minimum execution time: 24_297_000 picoseconds.
		Weight::from_parts(25_351_054, 3762)
			// Standard Error: 9_657
			.saturating_add(Weight::from_parts(52_125, 0).saturating_mul(m.into()))
			// Standard Error: 2_739
			.saturating_add(Weight::from_parts(280_405, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 43).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `325 + b * (1 ±0) + m * (40 ±0) + p * (78 ±0)`
		//  Estimated: `3929 + b * (1 ±0) + m * (29 ±1) + p * (74 ±0)`
		// Minimum execution time: 37_447_000 picoseconds.
		Weight::from_parts(40_392_851, 3929)
			// Standard Error: 98
			.saturating_add(Weight::from_parts(2_216, 0).saturating_mul(b.into()))
			// Standard Error: 5_134
			.saturating_add(Weight::from_parts(480_687, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 29).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 74).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Prime` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `350 + m * (33 ±0) + p * (55 ±0)`
		//  Estimated: `3813 + m * (34 ±0) + p * (56 ±0)`
		// Minimum execution time: 26_608_000 picoseconds.
		Weight::from_parts(27_599_682, 3813)
			// Standard Error: 10_650
			.saturating_add(Weight::from_parts(62_501, 0).saturating_mul(m.into()))
			// Standard Error: 3_021
			.saturating_add(Weight::from_parts(281_797, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 34).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 56).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Prime` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `MaintenanceMode::MaintenanceMode` (r:1 w:0)
	/// Proof: `MaintenanceMode::MaintenanceMode` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 100]`.
	/// The range of component `p` is `[1, 100]`.
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `345 + b * (1 ±0) + m * (40 ±0) + p * (78 ±0)`
		//  Estimated: `3948 + b * (1 ±0) + m * (30 ±1) + p * (74 ±0)`
		// Minimum execution time: 39_961_000 picoseconds.
		Weight::from_parts(42_599_549, 3948)
			// Standard Error: 106
			.saturating_add(Weight::from_parts(2_441, 0).saturating_mul(b.into()))
			// Standard Error: 5_561
			.saturating_add(Weight::from_parts(485_206, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 30).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 74).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `p` is `[1, 100]`.
	fn disapprove_proposal(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `359 + p * (32 ±0)`
		//  Estimated: `1844 + p * (32 ±0)`
		// Minimum execution time: 13_568_000 picoseconds.
		Weight::from_parts(14_298_538, 1844)
			// Standard Error: 1_876
			.saturating_add(Weight::from_parts(218_013, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::CostOf` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncilCollective::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncilCollective::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 20]`.
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 100]`.
	fn kill(d: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1413 + p * (55 ±0)`
		//  Estimated: `4880 + d * (5 ±1) + p * (55 ±0)`
		// Minimum execution time: 21_888_000 picoseconds.
		Weight::from_parts(23_838_118, 4880)
			// Standard Error: 2_776
			.saturating_add(Weight::from_parts(333_459, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 5).saturating_mul(d.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncilCollective::ProposalOf` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncilCollective::CostOf` (r:1 w:0)
	/// Proof: `TreasuryCouncilCollective::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn release_proposal_cost() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `846`
		//  Estimated: `4311`
		// Minimum execution time: 13_274_000 picoseconds.
		Weight::from_parts(13_987_000, 4311)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}
