name: Check licenses

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - name: Setup Rust toolchain
        uses: ./.github/workflow-templates/rust-toolchain
        with:
          toolchain: 1.88.0
      - name: Verify Licenses
        run: |
          cargo install cargo-license@0.7.0
          ./scripts/verify-licenses.sh
