name: Update Rust/TS bindings

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * 0" # Runs every Sunday at 5:30 AM UTC

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: blacksmith-32vcpu-ubuntu-2404
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Local build new Node
        uses: ./.github/workflow-templates/cargo-build
        with:
          blacksmith-sticky-sccache: "true"
          blacksmith-sticky-sccache-key: ${{ github.repository }}-sccache-typegen-${{ runner.os }}-${{ hashFiles('rust-toolchain') }}
      - name: Upload Node
        uses: actions/upload-artifact@v7
        with:
          name: moonbeam
          path: build

  update-typescript-api:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download Node
        uses: actions/download-artifact@v8
        with:
          name: moonbeam
          path: target/release
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 9
          run_install: false
          cache: true
          cache_dependency_path: pnpm-lock.yaml
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "test/.nvmrc"
          package-manager-cache: false
          registry-url: https://registry.npmjs.org/
      - name: Run Typegen
        run: |
          chmod uog+x target/release/moonbeam
          pnpm i
          cd test
          pnpm typegen
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          base: master
          branch: "update-typescript-api-${{ github.run_id }}"
          commit-message: "Update Rust/TS bindings"
          draft: true
          title: "Update Rust/TS bindings"
          reviewers: "moonsong-coredev"
          labels: "B0-silent,D2-notlive"
